module.exports = {
    STATUS_SUCCESS: 200,
    STATUS_CREATED: 201,
    STATUS_SERVER_ERROR: 500,
    STATUS_FORBIDDEN: 403,
    STATUS_NOTFOUND: 404,
    STATUS_NOT_ALLOWED: 405,
    STATUS_AUTHORIZED: 401
};